FROM almalinux:9
#ARG course="DevOps with AWS" \
# ENV course="DevOps with AWS" \
#     duraton="120hrs" \
#     trainer="shivakumar"
ENV course="DevOps with AWS" \
duraton="120hrs" 
RUN echo "Course: $course, duraton: $duraton"
CMD ["sleep","100"]