ARG version
FROM almalinux:${version}
#ARG course="DevOps with AWS" \
# ENV course="DevOps with AWS" \
#     duraton="120hrs" \
#     trainer="shivakumar"
ARG course="DevOps with AWS" \
duraton="120hrs" 
RUN echo "Course: $course, duraton: $duraton"
CMD ["sleep","100"]